Update patch set 18
Patch Set 18:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8870284850787679536
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/vboot/ui.h:1
        Falling back to three-way merge...
        Applied patch to 'src/vboot/ui.h' cleanly.
        error: patch failed: src/vboot/ui/layout.c:1
        Falling back to three-way merge...
        Applied patch to 'src/vboot/ui/layout.c' with conflicts.
        U src/vboot/ui/layout.c

Patch-set: 18
Tag: autogenerated:cq:full-run