Update patch set 5
Patch Set 5:

The following build(s) failed:

oak-paladin: The ChromeSDK stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret The CPEExport stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret The UploadTestArtifacts stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret The Archive stage failed: <class 'chromite.lib.gs.GSCommandError'>: return code: 1
AccessDeniedException: 403 Forbidden

Failed command "/b/cbuild/internal_master/.cache/common/gsutil_4.15.tar.gz/gsutil/gsutil -o 'Boto:num_ret in https://uberchromegw.corp.google.com/i/chromeos/builders/oak%20paladin/builds/2064

veyron_pinky-paladin: The BuildPackages stage failed: Packages failed in ./build_packages: sys-boot/coreboot in https://uberchromegw.corp.google.com/i/chromeos/builders/veyron_pinky%20paladin/builds/5247

Your change may have caused this failure. There are also other changes that may be at fault: 60 other changes. See the blamelist for more details.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 5