fix build error when DEBUG is enabled
firmware/lib/flash_ts.c: In function 'flash_ts_find_writeable_spot':
firmware/lib/flash_ts.c:180:5: error:
	implicit declaration of function 'VbExDebug' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors

BUG=None
TEST=`make` works
TEST=`make DEBUG=1` works
BRANCH=none

Original-Change-Id: Id529ca885828ca38d5230f41f81d4b87395c5e65
Reviewed-on: https://gerrit.chromium.org/gerrit/59654
Reviewed-by: Bill Richardson <wfrichar@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
(cherry picked from commit 05f5944a40dca2a92070f26dad0bfbb57f59aca1)

Change-Id: If26f83802ee78bb2c45a4f5984092f4647420033
Signed-off-by: Duncan Laurie <dlaurie@chromium.org>