vboot: remove -drop-ld-preload from qemu invocation
This flag is currently not supported in the qemu binary,
and causes qemu process to end with a return code of 1,
making all tests fail.

The inability to enable this flag is likely the cause
of all the warnings in test output:

  ERROR: ld.so: object 'libsandbox.so' from LD_PRELOAD
  cannot be preloaded (cannot open shared object file): ignored.

BUG=b:124141368, chromium:605348
TEST=make clean && make runtests
TEST=force QEMU_ARCH := ${ARCH} and run:
     FEATURES=test emerge-eve vboot_reference
BRANCH=none

Change-Id: Ie8c06da7a52638268d6ab318b591c995b18b98b3