futility: updater: Improve error message when key conflicts
Many firmware developers will try to flash a local built firmware (i.e,
DEV key signed) on a MP device (with write protection enabled).

The updater used to provide feedback like:

ERROR: verify_keyblock: Failed verifying key block.
INFO: Current (RO) firmware image has root key: ade780ffd0...732867181bae
WARNING: Target (RW) image is signed by rootkey: b11d74edd2...e1135b49e7f0.
ERROR: RW not signed by same RO root key
>> FAILED: Firmware updater aborted.

This is correctly identifying the root cause, but not helpful for
developers to figure out what to do, and may be confused with the DEV
re-key safety check (which needs --force).

Also, when developers try to do "--mode=factory --force", the message
was:

updater_setup_config: Factory mode needs WP disabled.

Where the 'WP' is again not clear enough.

With this change, we're improving the error messages so that:
 - Being consistent on 'root key' instead of 'rootkey'.
 - Being consistent for having period for error messages, except those
   ended with root key hash (for easier copy-paste).
 - Say 'Write Protection' instead of 'WP'.
 - When re-keying with WP enabled, print a better hint:
   "To change keys in RO area, you have to first remove write protection
   (go/cros-remove-wp)."

BUG=None
TEST=make futil; tests/futility/run_test_scripts.sh $(pwd)/build/futility
BRANCH=none

Change-Id: Ia74d7b113766d09428a4d0897918b4f17b4afae7