Update patch set 6
Patch Set 6:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8862155150084202592
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: Makefile:1
        Falling back to three-way merge...
        Applied patch to 'Makefile' with conflicts.
        U Makefile

Patch-set: 6
Tag: autogenerated:cq:dry-run