2load_android_kernel: Resolve Dev mode crash with self-signed images
This commit addresses an issue in the `vb2_load_android_kernel` function
where verification errors were incorrectly ignored in developer mode,
leading to crashes. The crash had the following signature:

    GptNextKernelEntry: GptNextKernelEntry likes partition 13
    vb2api_load_kernel: Found kernel entry at 17248258 size 131072
    vboot_avb_ops.c:292: ERROR: Mismatch in key length!
    avb_slot_verify.c:903: ERROR: vbmeta_a: Public key used to sign data
    rejected.
    vb2_is_fastboot_cmdline_valid: Wrong vb2_fastboot_cmdline magic (got
    0x0, expected 0x4c4d4346)
    vb2_is_fastboot_cmdline_valid: Wrong vb2_fastboot_cmdline magic (got
    0x0, expected 0x46434246)
    General Protection Fault Exception
    Error code: 0x0 - descriptor 0x0 in the GDT, internal to the CPU
    REG_IP:    0x000000003003aa1c
    REG_FLAGS: 0x0000000000010002
    REG_AX:    0x2f2e2d2c2b2a2929
    REG_BX:    0x0000000034088b80
    REG_CX:    0x0000000000000004
    REG_DX:    0x0000000000000006
    REG_SP:    0x00000000340887f0
    REG_BP:    0x0000000030133188
    REG_SI:    0x000000003005cef7
    REG_DI:    0x2f2e2d2c2b2a2928
    REG_R8:    0x0000000000000024
    REG_R9:    0xa800000000000000
    REG_R10:   0xa800000000000000
    REG_R11:   0x0000000034088660
    REG_R12:   0x00000000100b2000
    REG_R13:   0x000000006daa7008
    REG_R14:   0x0000000000000000
    REG_R15:   0x0000000000000000

The crash was due to the use of the `verify_data` variable, which, when
`need_keyblock_valid` is false, stays uninitialized in case of
`avb_slot_verify` failure.

The fix ensures that verification errors are ignored only when both
developer mode is active and verification errors are permissible,
preventing the crash.

Change-Id: I5fc8bd901c6feb4c50673a3cb7ad4ee1f0a2df06
Signed-off-by: Jeremy Compostella <jeremy.compostella@intel.com>