rust: build.rs: fix hardcoded sysroot path
Starting with glibc 2.41 we are finally enabling
float128 support. It's implementation is different
between x86 and arm architectures.

For example the x86 headers provide __float128 while
arm provides _Float128, therefore it's important to
include the proper headers for each architecture.

The vboot_reference-sys crate started failing with:

BOARD: arm64-generic (aarch64-cros-linux-gnu)
ERROR:
  /usr/include/bits/floatn.h:97:9: error: __float128 is not supported on this target
  Error: unable to generate bindings for vboot_host.h

Thus, with float128 we have uncovered a bug: bindgen
was including headers from the host instead of the
relevant sysroots.

Fix this by passing the --sysroot argument.

BUG=b:335699866
TEST=Local builds on host, amd64 (eve), arm; CQ;
BRANCH=none

Change-Id: I4e132d276da3571a055d807f502560668c1fe6b5
Signed-off-by: Adrian Ratiu <adrian.ratiu@collabora.com>