Update patch set 12
Patch Set 12:

There is a build error when building coreboot due to this patch (from coreboot.org) outside chroot environment

src/security/vboot/secdata_tpm.c:489:5: error: conflicting types for 'vb2ex_tpm_clear_owner'
 int vb2ex_tpm_clear_owner(struct vb2_context *ctx)

Do you see this issue as well ?  If yes, is there a fix for the same

Patch-set: 12
CC: Gerrit User 1128020 <1128020@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>