fuzzers: Fix builds with new clang
Clang is complaining about missing prototypes e.g.
tests/vb2_preamble_fuzzer.c:43:13: error: no previous
prototype for function 'vb2_check_padding'
[-Werror,-Wmissing-prototypes]

Add them to fix fuzzer builders.

BUG=chromium:1172055
TEST=tryjob

Signed-off-by: Manoj Gupta <manojgupta@google.com>
Change-Id: I9593e1f747939a38c33226f98570fa5423570362