futility: Fix body metadata hash verification
The "futility show" command was making a mistake when trying to verify
metadata hashes on RW partitions. By invoking:

CBFSTOOL=build/cbfstool build/util/futility/futility show
	 build/coreboot.rom

one could observe the following error:

Keyblock:                VBLOCK_B
  Signature:             valid
...
Firmware Preamble:
  Size:                  1688
...
  Body metadata hash:    SHA256:4da12eaeac99740a6...
ERROR: fw_show_metadata_hash: Failed to get metadata hash.
    Firmware body is corrupted or is not a valid CBFS.

When futility is invoked with --debug flag, the reason of error
becomes apparent:

DEBUG: subprocess_log_call: Run: /home/coreboot/coreboot/build/cbfstool
    VBLOCK_B print -kv -r FW_MAIN_B

VBLOCK_B file is not present, because futility passes the name of the
flashmap VBLOCK region being currently verified as a coreboot image
parameter to cbfstool, instead of the coreboot image path supplied as
futility parameter.

Fix it by adding a parameter with the coreboot image file path to the
fmap_show_fn functions. As a result the futility is able to
successfully verify the metadata hash:

  Body metadata hash:    SHA256:4da12eaeac99740a6a4f65adb769d66c6bf...
DEBUG: subprocess_log_call: Run: /home/coreboot/coreboot/build/cbfstool
    build/coreboot.rom print -kv -r FW_MAIN_B
Body verification succeeded.

Change-Id: I679effbf38e9dd8dbcb60ebaac4fbf94be0749f2
Signed-off-by: Michał Żygowski <miczyg94@gmail.com>