Update patch set 12
Patch Set 12:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8876192575472511792
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: firmware/2lib/2ui.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/2ui.c' with conflicts.
        error: patch failed: firmware/2lib/2ui_screens.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/2ui_screens.c' with conflicts.
        error: patch failed: firmware/2lib/include/2ui.h:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/include/2ui.h' cleanly.
        error: patch failed: tests/vb2_ui_action_tests.c:1
        Falling back to three-way merge...
        Applied patch to 'tests/vb2_ui_action_tests.c' cleanly.
        error: patch failed: tests/vb2_ui_tests.c:1
        Falling back to three-way merge...
        Applied patch to 'tests/vb2_ui_tests.c' cleanly.
        U firmware/2lib/2ui.c
        U firmware/2lib/2ui_screens.c

Patch-set: 12
Tag: autogenerated:cq:full-run