Update patch set 1
Patch Set 1:

The following build(s) failed:

alex paladin: The Archive stage failed: 

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_background.py", line 118, in run
    step()
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_stages.py", line 1371, in ArchivePayloads
    buildroot, target_image_path, update_payloads_dir)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/buildbot/cbuildbot_commands.py", line 1213, in GenerateFullPayload
    cros_build_lib.RunCommandCaptureOutput(cmd)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 1415, in RunCommandCaptureOutput
    return RunCommand(cmd, redirect_stdout=True, redirect_stderr=True, **kwds)
  File "/b/cbuild/x86-alex-paladin-bin-master/chromite/lib/cros_build_lib.py", line 433, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 1
2012/07/17 11:10:35 - cros_generate_test_payloads.py - INFO    : Base image not specified. Using target as base image.
2012/07/17 11:10:35 - cros_generate_test_payloads.py - INFO    : Generating updates required for this test suite in parallel.
2012/07/17 11:10:35 - cros_generate_test_payloads.py - INFO    : Generating an unsigned full payload to /b/cbuild/x86-alex-paladin-bin-master/src/build/images/x86-alex/latest-cbuildbot/chromiumos_test_image.bin
2012/07/17 11:10:41 - cros_generate_test_payloads.py - ERROR   : tee: /sys/fs/cgroup/cros/cros/cbuildbot/cbuildbot:21325/cros_sdk:46068/tasks: No such file or directory
Group cros/cbuildbot/cbuildbot:21325/cros_sdk:46068 was removed under our feet; pool shutdown is underway

Traceback (most recent call last):
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 476, in <module>
    main()
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 471, in main
    cache = generator.GeneratePayloads()
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 319, in GeneratePayloads
    results = ProcessOutput(log_files, error_codes)
  File "/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py", line 280, in ProcessOutput
    'Failed to generate a required update.')
crostestutils.generate_test_payloads.payload_generation_exception.PayloadGenerationException: Failed to generate a required update.

Failed command "['/b/cbuild/x86-alex-paladin-bin-master/src/platform/crostestutils/generate_test_payloads/cros_generate_test_payloads.py', '--target=/b/cbuild/x86-alex-paladin-bin-master/src/build/images/x86-alex/latest-cbuildbot/chromiumos_test_image.bin', '--full_payload', '--nplus1_archive_dir=/tmp/cbuildbot-tmpgtZ99N/cbuildbot7JnGyp']", cwd=None, extra env=None
 in http://uberchromegw.corp.google.com/i/chromeos/builders/alex%20paladin/builds/6774

Your change may have caused this failure. There are also other changes that may be at fault: jimhebert:27563:61a964fa, jimhebert:27656:6cb99675, keescook:27541:737165d2, kimarie.hoot:21942:dcd67574, vbendeb:21949:2db130f3, wiley:27537:06d29b0c

Please check whether the failure is your fault. If your change is not at fault, you may mark it as ready again.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 1