futility/platform_csme: add missing USE_FLASHROM guards
Fixes:
build/futility/platform_csme.o: in function `find_fmba':
futility/platform_csme.c:42: undefined reference to `find_firmware_section'
build/futility/platform_csme.o: in function `unlock_csme':
futility/platform_csme.c:200: undefined reference to `get_firmware_image_temp_file'
futility/platform_csme.c:230: undefined reference to `reload_firmware_image'

Change-Id: I74140d38d119f2a0e6b8cf8eef3f9f05cd43bbd7
Signed-off-by: James Hilliard <james.hilliard1@gmail.com>