Update patch set 5
Patch Set 5: Verified-1

breaks the CQ:

 depthcharge-777/build/external/vboot/vboot_fw.a(cgptlib_internal.o): In function `GetEntryPriority':
 depthcharge-777/vboot_reference/firmware/lib/cgptlib/cgptlib_internal.c:373: undefined reference to `VbExOverrideGptEntryPriority'

Patch-set: 5