Update patch set 19
Patch Set 19:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8870284850787679536
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: src/vboot/ui.h:1
        Falling back to three-way merge...
        Applied patch to 'src/vboot/ui.h' cleanly.
        error: patch failed: src/vboot/ui/layout.c:1
        Falling back to three-way merge...
        Applied patch to 'src/vboot/ui/layout.c' with conflicts.
        U src/vboot/ui/layout.c

Patch-set: 19
Tag: autogenerated:cq:full-run
Attention: {"person_ident":"Gerrit User 1383774 \u003c1383774@3ce6091f-6c88-37e8-8c75-72f92ae8dfba\u003e","operation":"ADD","reason":"Someone else replied on the change"}