tests: fix build errors with USE_FLASHROM=0 Android Bringup: See http://go/android-fw-sync
Test `vb2_host_flashrom_tests` uses libflashrom, thus it fails to build
with `USE_FLASHROM=0`:

```
.../tests/vb2_host_flashrom_tests.o: in function `test_read_whole_chip':
.../tests/vb2_host_flashrom_tests.c:152:(.text.startup.main+0x48): undefined reference to `flashrom_read'
.../tests/vb2_host_flashrom_tests.o: in function `test_read_region':
.../tests/vb2_host_flashrom_tests.c:175:(.text.startup.main+0x195): undefined reference to `flashrom_read'
.../tests/vb2_host_flashrom_tests.o: in function `test_read_failure':
.../tests/vb2_host_flashrom_tests.c:200:(.text.startup.main+0x2e9): undefined reference to `flashrom_read'
.../tests/vb2_host_flashrom_tests.o: in function `test_write_whole_chip':
.../tests/vb2_host_flashrom_tests.c:216:(.text.startup.main+0x33c): undefined reference to `flashrom_write'
.../tests/vb2_host_flashrom_tests.o: in function `test_write_region':
.../tests/vb2_host_flashrom_tests.c:243:(.text.startup.main+0x49e): undefined reference to `flashrom_write'
.../tests/vb2_host_flashrom_tests.o: in function `test_write_failure':
.../tests/vb2_host_flashrom_tests.c:270:(.text.startup.main+0x614): undefined reference to `flashrom_write'
```

Build it conditionally on this variable to fix that.

BRANCH=None
BUG=None
TEST=`make clean; make USE_FLASHROM=0 -j$(nproc) tests`

(cherry picked from commit c51cbc4ace85a2ed24c8786022ef0c6ca0bd6f47)

Original-collect2: error: ld returned 1 exit status
Change-Id: I17ad4843e8db024b554ca7386e68103c99d1619a
Original-Signed-off-by: Mauricio Faria de Oliveira <mfo@igalia.com>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/6309491
Original-Commit-Queue: Julius Werner <jwerner@chromium.org>
Original-Tested-by: Julius Werner <jwerner@chromium.org>
Original-Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Original-Reviewed-by: Julius Werner <jwerner@chromium.org>
GitOrigin-RevId: c51cbc4ace85a2ed24c8786022ef0c6ca0bd6f47
Cr-Build-Id: 8718012716580879665
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8718012716580879665
Copybot-Job-Name: android-main-vboot_reference-copybot-downstream
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/6444851
Reviewed-by: Jon Murphy <jpmurphy@google.com>
Commit-Queue: Grzegorz Bernacki <bernacki@google.com>
Tested-by: Grzegorz Bernacki <bernacki@google.com>