Update patch set 11
Patch Set 11:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8876637333496261888
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: firmware/2lib/2ui.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/2ui.c' cleanly.
        error: patch failed: firmware/2lib/2ui_screens.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/2ui_screens.c' cleanly.
        error: patch failed: tests/vb2_ui_tests.c:1
        Falling back to three-way merge...
        Applied patch to 'tests/vb2_ui_tests.c' with conflicts.
        U tests/vb2_ui_tests.c

Patch-set: 11
Tag: autogenerated:cq:full-run