Update patch set 5
Patch Set 5:

Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8884286382591731840
    Merge conflict detected! Please rebase and retry.
    
        error: Failed to merge in the changes.
        hint: Use 'git am --show-current-patch' to see the failed patch
        CONFLICT (content): Merge conflict in firmware/lib/vboot_api_kernel.c

Patch-set: 5
Tag: autogenerated:cq:full-run