Split UI parts out of fwlib for host builds
They're not needed on the host (except for tests) and they trigger
a bug in GCC 4.9 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=49132).
This way futility remains buildable with such an old host compiler,
even if firmware builds and serious work (with tests) needs a newer
compiler.

Error message averted (sample):
firmware/2lib/2ui_screens.c:17:32: error: initializer element is not constant
 #define MENU_ITEMS(a) ((struct vb2_menu){ \
                                ^
firmware/2lib/2ui_screens.c:1231:10: note: in expansion of macro 'MENU_ITEMS'
  .menu = MENU_ITEMS(diagnostics_memory_items),
          ^

(cherry picked from commit edd222428715125b9ef2a9a8a064fc32a0d0bd24)

Change-Id: Ic5bd16e4d252df4297d57c5d41436f4322a1445c
Original-Signed-off-by: Patrick Georgi <pgeorgi@google.com>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/2553422
Original-Tested-by: Patrick Georgi <pgeorgi@chromium.org>
Original-Commit-Queue: Patrick Georgi <pgeorgi@chromium.org>
Original-Reviewed-by: Julius Werner <jwerner@chromium.org>
GitOrigin-RevId: edd222428715125b9ef2a9a8a064fc32a0d0bd24