tests: skip flashrom-related tests with USE_FLASHROM=0
Some tests execute `futility flash|read|update|gbb --flash` commands,
which are unavailable if "futility was built without flashrom support",
thus fail:

```
$ make clean; make -j$(nproc) USE_FLASHROM=0 runtests 2>&1 \
  | grep -o 'FAILED.*'
FAILED (1). Stdout is recorded in /.../test_flash_util.sh.stdout
FAILED (1). Stdout is recorded in /.../test_gbb_utility.sh.stdout
FAILED (1). Stdout is recorded in /.../test_update.sh.stdout
FAILED (1). Stdout is recorded in /.../test_read.sh.stdout
```

Fortunately, the commands print an error about it:
```
FATAL: do_flash: futility was built without flashrom support, ...
FATAL: do_read: futility was built without flashrom support, ...
FATAL: do_update: futility was built without flashrom support, ...
ERROR: do_gbb: futility was built without flashrom support
```

Skip those tests by checking for such error in the command.

BRANCH=None
BUG=None
TEST=`make clean; make -j$(nproc) USE_FLASHROM=0 runtests`

Change-Id: I1c1031f591c32bb5ccc311ff622c41d04b858012
Signed-off-by: Mauricio Faria de Oliveira <mfo@igalia.com>