make_dev_firmware.sh: correct flashrom examples
I was following the advice given in these examples and saw:

  # flashrom -p bios -w /mnt/stateful_partition/backups/bios_SAMUS_TEST_8028_20190628_100324.fd
  flashrom v0.9.9  : cc7cca2 : Jun 15 2019 04:36:54 UTC on Linux 4.14.129 (x86_64)
  Error: Unknown programmer bios.
  Please run "flashrom --help" for usage info.

As you can see in flashrom_bios() in that same file, the "programmer"
argument in flashrom that you need to flash the BIOS is "host" not
"bios":

  # flashrom -p host -w /tmp/bios_SAMUS_TEST_8028_20190628_100324.fd
  flashrom v0.9.9  : 2d00129 : Jun 27 2019 15:16:55 UTC on Linux 4.14.129 (x86_64)
  flashrom v0.9.9  : 2d00129 : Jun 27 2019 15:16:55 UTC on Linux 4.14.129 (x86_64)
  Calibrating delay loop... OK.
  coreboot table found at 0x7ce3a000.
  ...
  Erasing and writing flash chip... SUCCESS

BUG=none
TEST=successfully flashed a backup BIOS image using flashrom
BRANCH=none

Change-Id: Ib1e10c1e06ad84714853953702328c4f4dadebe7
Signed-off-by: Ross Zwisler <zwisler@google.com>