Update patch set 4
Patch Set 4: Verified+1 Commit-Queue+2

Not quite sure about the error... maybe it was caused by some bad auto-rebasing?

vboot_reference-1.0-r1926: firmware/2lib/2ui_screens.c:194:13: error: redefinition of
vboot_reference-1.0-r1926:       'recovery_to_dev_init'
vboot_reference-1.0-r1926: vb2_error_t recovery_to_dev_init(struct vb2_ui_context *ui)
vboot_reference-1.0-r1926:             ^
vboot_reference-1.0-r1926: firmware/2lib/2ui_screens.c:99:13: note: previous definition is here
vboot_reference-1.0-r1926: vb2_error_t recovery_to_dev_init(struct vb2_ui_context *ui)
vboot_reference-1.0-r1926:             ^
vboot_reference-1.0-r1926: firmware/2lib/2ui_screens.c:214:13: error: redefinition of
vboot_reference-1.0-r1926:       'vb2_ui_recovery_to_dev_action'
vboot_reference-1.0-r1926: vb2_error_t vb2_ui_recovery_to_dev_action(struct vb2_ui_context *ui)
vboot_reference-1.0-r1926:             ^
vboot_reference-1.0-r1926: firmware/2lib/2ui_screens.c:119:13: note: previous definition is here
vboot_reference-1.0-r1926: vb2_error_t vb2_ui_recovery_to_dev_action(struct vb2_ui_context *ui)
vboot_reference-1.0-r1926:             ^
vboot_reference-1.0-r1926: 2 errors generated.

Patch-set: 4
Reviewer: Gerrit User 1126709 <1126709@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=+2
Label: Verified=+1