treewide: Put the static keyword at the beginning of declarations
In order to comply with the more recent style of declarations, put the
static keyword at the beginning.

Fixes following GCC error when the related flag on coreboot upstream is
set:

  error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]

(cherry picked from commit 32402941c0afdb5bf50d6e3c11548ecb1ac80544)

Change-Id: I81d72eeef3c01927bb691374054721b57979cbe0
Original-Signed-off-by: Felix Singer <felixsinger@posteo.net>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/5173314
Original-Tested-by: Julius Werner <jwerner@chromium.org>
Original-Reviewed-by: Julius Werner <jwerner@chromium.org>
Original-Commit-Queue: Julius Werner <jwerner@chromium.org>
GitOrigin-RevId: 32402941c0afdb5bf50d6e3c11548ecb1ac80544
Cr-Build-Id: 8739997580243611025
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739997580243611025
Copybot-Job-Name: android-main-fw-nissa-vboot_reference-copybot-downstream