Update patch set 3
Patch Set 3:

I run into the following break trying to build coreboot on master.  Am I missing something?

    CC            futility/cmd_update.o
futility/cmd_dump_fmap.c:447:4: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                        __attribute__ ((fallthrough));
                        ^
futility/cmd_dump_fmap.c:510:4: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                        __attribute__ ((fallthrough));
                        ^
2 errors generated.
    CC            futility/cmd_validate_rec_mrc.o
make[1]: *** [Makefile:1105: /build/volteer/tmp/portage/sys-boot/coreboot-9999/work/coreboot-9999/build_serial-volteer/util/futility/build/futility/cmd_dump_fmap.o] Error 1
make[1]: *** Waiting for unfinished jobs....
futility/cmd_sign.c:724:4: error: declaration does not declare anything [-Werror,-Wmissing-declarations]
                        __attribute__ ((fallthrough));
                        ^
1 error generated.

Patch-set: 3
CC: Gerrit User 1185940 <1185940@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>