Update patch set 3
Patch Set 3:

Dry run: Failed builds:
  luci.chromeos.cq/cq-orchestrator JOB_FAILED https://cr-buildbucket.appspot.com/build/8881147212451745392
    Merge conflict detected! Please rebase and retry.
    
        error: patch failed: firmware/2lib/include/2api.h:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/include/2api.h' cleanly.
        error: patch failed: firmware/2lib/include/2return_codes.h:1
        Falling back to three-way merge...
        Applied patch to 'firmware/2lib/include/2return_codes.h' with conflicts.
        error: patch failed: firmware/lib/vboot_ui_legacy_clamshell.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/lib/vboot_ui_legacy_clamshell.c' with conflicts.
        error: patch failed: firmware/lib/vboot_ui_legacy_menu.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/lib/vboot_ui_legacy_menu.c' with conflicts.
        error: patch failed: firmware/lib/vboot_ui_legacy_wilco.c:1
        Falling back to three-way merge...
        Applied patch to 'firmware/lib/vboot_ui_legacy_wilco.c' with conflicts.
        error: patch failed: tests/vboot_legacy_clamshell_tests.c:1
        Falling back to three-way merge...
        Applied patch to 'tests/vboot_legacy_clamshell_tests.c' cleanly.
        error: patch failed: tests/vboot_legacy_menu_tests.c:1
        Falling back to three-way merge...
        Applied patch to 'tests/vboot_legacy_menu_tests.c' cleanly.
        U firmware/2lib/include/2return_codes.h
        U firmware/lib/vboot_ui_legacy_clamshell.c
        U firmware/lib/vboot_ui_legacy_menu.c
        U firmware/lib/vboot_ui_legacy_wilco.c

Patch-set: 3
Tag: autogenerated:cq:dry-run