futility: Fix build with a single RW partition and CBFS verification
If RW A FMAP layout is used, futility fails to sign the coreboot image
when VBOOT_CBFS_INTEGRATION is enabled. The exact error message:

FATAL: image_check_and_prepare_cbfs: CBFS metadata hash not found in
area FW_MAIN_B. It is required for images with VBOOT_CBFS_INTEGRATION

Do not raise the fatal error if metadatahash is not available. Simply
mark the metadatahash algorithm as invalid, which will result in
markign the RW B firmware as invalid and gracefully skipping any
actions related to it:

ERROR: prepare_slot: FW_MAIN_B area not found in FMAP
INFO: sign_bios_at_end: BIOS image does not have FW_MAIN_B.
      Signing only FW_MAIN_A
    FLASHMAP Layout generated for RO and A partition.

TEST=Successfully build an image with VBOOT_CBFS_INTEGRATION and
RW A partition flashmap layout.

Change-Id: I3bcf04aa88b35f43daae0c7bd3793f0d19957017
Signed-off-by: Michał Żygowski <miczyg94@gmail.com>