flashrom_drv,futility: support upstream flashrom with USE_FLASHROM_UPSTREAM=1
Building from source in some distros fails due to code dependencies in
patches not available in libflashrom upstream or in the distro package:

```
host/lib/flashrom_drv.c: In function ‘flashrom_get_info’:
host/lib/flashrom_drv.c:416:9: error: implicit declaration of function
	‘flashrom_flash_getinfo’; did you mean ‘flashrom_flash_getsize’?
	[-Wimplicit-function-declaration]
  416 |         flashrom_flash_getinfo(flashctx, &info);
      |         ^~~~~~~~~~~~~~~~~~~~~~
      |         flashrom_flash_getsize

host/lib/flashrom_drv.c:420:20: error: ‘struct flashrom_flashchip_info’
	has no member named ‘manufacture_id’
  420 |         *vid = info.manufacture_id;
      |                    ^

host/lib/flashrom_drv.c:421:20: error: ‘struct flashrom_flashchip_info’
	has no member named ‘model_id’
  421 |         *pid = info.model_id;
      |                    ^
```

Add make variable USE_FLASHROM_UPSTREAM (default: 0/disabled) in order
to conditionally disable such code and fix build errors out of cros_sdk.

BRANCH=None
BUG=None
TEST=`make -j$(nproc) USE_FLASHROM_UPSTREAM=1` finishes successfully on
Ubuntu Plucky (to be 25.04), and `make -j$(nproc)` on cros_sdk as well.
And `./build/futility/futility help flash 2>&1 | grep -- '--flash-info'`
only matches without USE_FLASHROM_UPSTREAM=1.

Change-Id: Ia419276619ae399e9fdc5c18e939f69e72eb2625
Signed-off-by: Mauricio Faria de Oliveira <mfo@igalia.com>