scripts/image_signing: Add swap_ec_rw
Move the script platform/dev/contrib/firmware/swap_ec_rw to
vboot_reference, and install it to /usr/share/vboot/bin/ in CrOS SDK,
for both manual run and platform/firmware/pack_firmware.py.

Usage:

 swap_ec_rw -i ${AP_IMAGE} -e ${EC_IMAGE}

The above command will replace the "ecrw" CBFS file within ${AP_IMAGE}
with ${EC_IMAGE} (and also update "ecrw.hash").

For now, only Zephyr EC is supported. Running the command with a CrOS EC
will produce the following error:

 ERROR: normal_fmap: FMAP section RW_FW not found

Add swap_ec_rw_tests.sh and some data files to test the new script.

BUG=b:325886850
TEST=swap_ec_rw -i image-brya0.bin -e ec.bin
TEST=FEATURES=test emerge-brya vboot_reference
BRANCH=none

(cherry picked from commit 4ca605344fe227debf363c6e84b16987263a9c97)

Cq-Depend: chromium:5409975
Original-Disallow-Recycled-Builds: tael-cq, tatl-cq
Change-Id: I7bad328f5aaacfdd386a666b31348f3fae6eac8f
Original-Signed-off-by: Yu-Ping Wu <yupingso@chromium.org>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/5408908
Original-Reviewed-by: Julius Werner <jwerner@chromium.org>
GitOrigin-RevId: 4ca605344fe227debf363c6e84b16987263a9c97
Cr-Build-Id: 8739997580243611025
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8739997580243611025
Copybot-Job-Name: android-main-fw-nissa-vboot_reference-copybot-downstream