host: Fix compilation error with GCC Android Bringup: See http://go/android-fw-sync
This commit addresses an issue with variable initialization in the
vb21_sign_data() function introduced by commit ab654c4a5829 ("vb21: load
private key before signing"). When the vb_keyb_from_private_key function
fails, the code jumps to the done label, which attempts to free buf that
was not declared nor assigned at the time of the jump.

By declaring and initializing the buf variable alongside sig_digest, the
following compilation error and potential runtime issues are being
addressed:

    host/lib21/host_signature.c:207:17: error: 'buf' may be used
    uninitialized in this function [-Werror=maybe-uninitialized]
    207 | free(buf);
        | ^~~~~~~~~

BUG=b:414365647
TEST=Successful build with GCC

(cherry picked from commit 3ef2f5b975e35018521a2f6488e114a57dda54b9)

Change-Id: I1f950d4bb8835edd67de4589553a2cdee19d2397
Original-Signed-off-by: Jeremy Compostella <jeremy.compostella@intel.com>
Original-Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/vboot_reference/+/6495787
Original-Reviewed-by: Grzegorz Bernacki <bernacki@google.com>
Original-Tested-by: Zhixing Ma <zhixing.ma@intel.com>
Original-Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>
Original-Reviewed-by: Benjamin Shai <bshai@google.com>
Original-Reviewed-by: Zhixing Ma <zhixing.ma@intel.com>
GitOrigin-RevId: 3ef2f5b975e35018521a2f6488e114a57dda54b9
Cr-Build-Id: 8716268725449679121
Cr-Build-Url: https://cr-buildbucket.appspot.com/build/8716268725449679121
Copybot-Job-Name: android-main-fw-brya-vboot_reference-copybot-downstream