Update patch set 5
Patch Set 5:

> Patch Set 5:
> 
> I'm going to try to run this on a Grunt, to be sure

Also building this on grunt too. I get an error building this though:

host/lib/crossystem.c:106:2: error: implicit declaration of function 'vb2api_init' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        vb2api_init(fake_workbuf, sizeof(fake_workbuf), &fake_ctx);
        ^

Gonna try repo sync in case something is out of date. Looks like that function is declared in 2api.h which is #included in crossystem.c

Patch-set: 5
Reviewer: Gerrit User 1196554 <1196554@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>