Update patch set 6
Patch Set 6:

The Commit Queue failed to apply your change in https://luci-milo.appspot.com/buildbot/chromeos/master-paladin/17922 . CL:942031 failed to apply due to a CQ issue: Unhandled exception occurred while applying changes: <class 'chromite.lib.cros_build_lib.RunCommandError'>: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/infra/lucifer
fatal: remote error: Gerrit error

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/infra/lucifer'], cwd=/b/c/cbuild/repository/infra/lucifer
Traceback (most recent call last):
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 603, in TaskRunner
    task(*x, **task_kwargs)
  File "/b/c/cbuild/repository/chromite/lib/parallel.py", line 801, in <lambda>
    fn = lambda idx, task_args: out_queue.put((idx, task(*task_args)))
  File "/b/c/cbuild/repository/chromite/cbuildbot/patch_series.py", line 139, in _FetchChangesForRepo
    git.RunGit(repo, cmd, print_cmd=True)
  File "/b/c/cbuild/repository/chromite/lib/git.py", line 824, in RunGit
    ['git'] + cmd, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/retry_util.py", line 244, in GenericRetry
    return _run()
  File "/b/c/cbuild/repository/chromite/lib/retry_util.py", line 177, in _Wrapper
    ret = func(*args, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/retry_util.py", line 243, in _run
    return functor(*args, **kwargs)
  File "/b/c/cbuild/repository/chromite/lib/cros_build_lib.py", line 658, in RunCommand
    raise RunCommandError(msg, cmd_result)
RunCommandError: return code: 128; command: git fetch -f https://chromium-review.googlesource.com/chromiumos/infra/lucifer
fatal: remote error: Gerrit error

cmd=['git', 'fetch', '-f', u'https://chromium-review.googlesource.com/chromiumos/infra/lucifer'], cwd=/b/c/cbuild/repository/infra/lucifer


To be safe, we have kicked out all of the CLs, so that the commit queue does not go into an infinite loop retrying patches.

Commit queue documentation: http://www.chromium.org/developers/tree-sheriffs/sheriff-details-chromium-os/commit-queue-overview

Patch-set: 6